import TableComponent, { TableData } from "@/components/TableComponent";

const SectionTable = () => {
  const data: TableData[] = [
    {
      id: 1,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 2,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 3,
      name: "Edgardo",
      createdAt: "25-11-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 4,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 5,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 6,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 7,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 8,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 9,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 10,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 12,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 13,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 14,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 15,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 16,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 17,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 18,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 19,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 20,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 21,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 22,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 23,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
    {
      id: 24,
      name: "Test notifications",
      createdAt: "25-10-2021",
      file: "Download Icon",
      fileLink: "http://www.digh.org",
      status: "Completed",
      user: "Adnan",
      hash: "985eb5313dxdl153l3sx13lx2azaxsc",
      type: "None",
    },
  ];

  const headers = [
  "Id",
  "Name",
  "Created At",
  "File",
  "File Link",
  "Status",
  "User",
  "Hash",
  "Type",
  "Actions",
];

  return (
    <div>
      <TableComponent
        headerTable={headers}
        data={data}
      />
    </div>
  );
};

export default SectionTable;
